# P1Monitor compose-file

version: "3.2" #Version 3.2 an and later
services:
  web:
    container_name: p1monitor
    image: p1monitor-docker
    build: .
    restart: always
    cap_add:
      - SYS_NICE
    devices:
      - /dev/ttyUSB0
      - /dev/gpiomem
    environment: []
    hostname: p1mon
    ports:
      - "9595:80"
      - "10721:10721"
      - "40721:40721"
    volumes:
      - type: bind
        source: /opt/p1mon/data
        target: /p1mon/data
      - type: bind
        source: /opt/p1mon/usbdisk
        target: /p1mon/usb
    tmpfs:
      - /tmp
      - /run
      - /p1mon/mnt/ramdisk
